spring.application.name=Practice-project
server.port=2004



spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/codingprofile
spring.datasource.username=root
spring.datasource.password=root
# Tells Hibernate to automatically create tables if they do not exist
spring.jpa.hibernate.ddl-auto=update

# Optional: Prints the SQL statements to the Eclipse console so you can see the table creation happen
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.data.redis.host=${redishost}
spring.data.redis.port=6379
spring.cache.type=redis

spring.security.user.name=kamesh
spring.security.user.password=kamesh

# Brevo SMTP Configuration
spring.mail.host=smtp-relay.brevo.com
spring.mail.port=587
spring.mail.username=af659b001@smtp-brevo.com
spring.mail.password=xsmtpsib-cdfaf88b5cbcf09902e93255f722f2475973c4641f0c477266b14c7f5f7b5859-gGr8fCs59ISka9ZS

# Mail Properties
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Thymeleaf Template Settings
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html